export const FORMULARIO_PROYECTO = "PROYECTO_FORM";
export const NOSHOWFORM_NEWPROYECT = "NOSHOWFORM_NEWPROYECT";
export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";

export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const EDITAR_TAREA = "EDITAR_TAREA";
export const ESTADO_TAREA = "ESTADO_TAREA";
export const ACTUALIZAR_TAREA = "ACTUALIZAR_TAREA";

export const AGREGAR_NOTA = "AGREGAR_NOTA";
export const ELIMINAR_NOTA = "ELIMINAR_NOTA";
export const BUSQUEDA = "BUSQUEDA";
