import type { NextPage } from "next";
import Head from "next/head";
// font-family: '', ;
// font-family: '', ;
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Book-ez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-red-400 font-quickSand">Hola guapo Q</h1>
    </div>
  );
};

export default Home;
