import type { NextPage } from "next";
import Head from "next/head";
import { NavBar } from "../components/homePage/NavBar";
const Home: NextPage = () => {
  return (
    <div className="w-full min-h-screen">
      <Head>
        <title>Book-ez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <NavBar />
    </div>
  );
};

export default Home;
